### ISSUE TITLE
TALOS Security Advisory for FreyrSCADA (TALOS-2020-1174) 

### ISSUE THREAD

**Issue by CiscoTalos** [FreyrSCADA/DNP3#2]
Is there a point of contact handling security vulnerabilities?  We issued an email on 2020-10-22 regarding security vulnerability affecting FreyrSCADA IEC-60879-5-104 server and to date have not received a response.
If there's a way to mark this issue private for security purposes, we can also submit the advisory in GitHub.

**Comment by FreyrSCADA** [comment]
solved in IEC 104 Server simulator and verified by ciscotalos. closed

https://www.freyrscada.com/iec-60870-5-104-Server-Simulator.php

https://www.freyrscada.com/iec-60870-5-104-Client-Simulator.php
